"""Metrics JSON + standalone HTML report for judges/operators."""

from __future__ import annotations

import json
from pathlib import Path

from .risk import LEVELS


def sparkline_svg(
    values: list[float], width: int = 640, height: int = 80, color: str = "#e05252", label: str = ""
) -> str:
    if not values:
        return "<svg></svg>"
    vmax = max(max(values), 1e-6)
    n = len(values)
    pts = " ".join(
        f"{(i / max(n - 1, 1)) * width:.1f},{height - (v / vmax) * (height - 12):.1f}"
        for i, v in enumerate(values)
    )
    return (
        f'<svg viewBox="0 0 {width} {height}" width="100%" height="{height}" '
        f'preserveAspectRatio="none" role="img" aria-label="{label}">'
        f'<polyline points="{pts}" fill="none" stroke="{color}" stroke-width="2"/>'
        f'<text x="4" y="14" font-size="11" fill="#888">{label} (max {max(values):.1f})</text>'
        "</svg>"
    )


def write_metrics(path: Path, summary: dict) -> None:
    path.write_text(json.dumps(summary, indent=2))


def write_report(path: Path, summary: dict, video_filename: str) -> None:
    frames = summary["frames"]
    counts = [f["count"] for f in frames]
    peaks = [f["max_density"] for f in frames]
    alerts = summary["alerts"]
    incidents = summary.get("incidents", [])

    alert_rows = (
        "".join(
            f"<tr><td>{i + 1}</td><td>{a['start_t']:.1f}s</td><td>{a['end_t']:.1f}s</td>"
            f"<td>{a['peak_density']:.1f} p/m&sup2;</td></tr>"
            for i, a in enumerate(alerts)
        )
        or '<tr><td colspan="4">No crush episodes detected</td></tr>'
    )

    def _outcome(inc: dict) -> str:
        if inc["end_t"] is None:
            return "<b>ongoing at video end</b>"
        if inc.get("recovered"):
            return f"recovered {inc['end_t']:.1f}s"
        return f"track lost {inc['end_t']:.1f}s"

    incident_rows = (
        "".join(
            f"<tr><td>{i + 1}</td><td>{inc['start_t']:.1f}s</td>"
            f"<td>{inc['confirmed_t']:.1f}s</td>"
            f"<td>{_outcome(inc)}</td>"
            f"<td>{inc['zone']}</td><td>{inc['peak_down_s']:.1f}s</td></tr>"
            for i, inc in enumerate(incidents)
        )
        or '<tr><td colspan="6">No person-down incidents detected</td></tr>'
    )

    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GuardianEye Report</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; margin: 2rem auto;
         max-width: 860px; padding: 0 1rem; background: #101216; color: #e8e8e8; }}
  h1 {{ color: #ff6b6b; }} h2 {{ margin-top: 2rem; }}
  .stats {{ display: flex; gap: 1rem; flex-wrap: wrap; }}
  .stat {{ background: #1a1e26; border-radius: 10px; padding: 1rem 1.4rem;
          flex: 1; min-width: 140px; }}
  .stat b {{ display: block; font-size: 1.6rem; }}
  table {{ border-collapse: collapse; width: 100%; }}
  td, th {{ border-bottom: 1px solid #2a2f3a; padding: .5rem .7rem; text-align: left; }}
  video {{ width: 100%; border-radius: 10px; }}
  .foot {{ color: #777; font-size: .85rem; margin-top: 2.5rem; }}
</style></head><body>
<h1>GuardianEye &mdash; Stadium Safety Analysis</h1>
<p>Source: <code>{summary["input"]}</code> &middot; {summary["n_frames"]} frames
 &middot; {summary["fps"]:.0f} fps &middot; depth: {summary.get("depth_source", "none")}
 &middot; status: <b>{LEVELS[summary["worst_level"]]}</b></p>
<video controls src="{video_filename}"></video>
<div class="stats">
  <div class="stat"><b>{summary["peak_count"]}</b>peak people in frame</div>
  <div class="stat"><b>{summary["peak_density"]:.1f}</b>peak density (p/m&sup2;)</div>
  <div class="stat"><b>{len(incidents)}</b>medical incidents</div>
  <div class="stat"><b>{len(alerts)}</b>crush episodes</div>
  <div class="stat"><b>{summary["proc_fps"]:.1f}</b>processing fps</div>
</div>
<h2>People in frame</h2>{sparkline_svg([float(c) for c in counts], color="#5aa9e6", label="count")}
<h2>Peak density</h2>{sparkline_svg(peaks, color="#e05252", label="people/m&sup2;")}
<h2>Person-down incidents</h2>
<table><tr><th>#</th><th>First down</th><th>Confirmed</th><th>Outcome</th><th>Zone</th>
<th>Max down-time</th></tr>{incident_rows}</table>
<h2>Crush episodes</h2>
<table><tr><th>#</th><th>Start</th><th>End</th><th>Peak density</th></tr>{alert_rows}</table>
<p class="foot">Thresholds used: {summary["thresholds"]} people/m&sup2;
 (SAFE / MODERATE / HIGH / CRITICAL). Anonymous detection &mdash; no faces are
 identified or stored. Generated by GuardianEye.</p>
</body></html>"""
    path.write_text(html)
